### ISSUE TITLE
Chapter 7

### ISSUE THREAD

**Issue by ChristianGiupponi** [FabienSerny/mymodcarrier#1]
Hi,
In cap 7 you refer to an API folder, where can I find it?

**Comment by FabienSerny** [comment]
Hi,
It's not the first time someone brings this problem to me.
It seems that my editor forgot to join this part of the code with the book.
I'll post it here in a few minutes.

**Comment by FabienSerny** [comment]
Hi,
We will add the code for download on our website:
http://www.froggy-commerce.com/en/content/8-book-on-prestashop-module-development
Meanwhile, you can download it on the Packt website here just by entering your e-mail : 
https://www.packtpub.com/books/content/support/16225
(I checked, they added the "api" directory in chapter 7)

**Comment by ChristianGiupponi** [comment]
Great!
Thanks again, just downloaded from packtpub!
